### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by megidont** [Rinnegatamante/vitaQuake#15] opened 2016-08-23 22:45 UTC
Here are those issues, reposted from the Wololo thread!
1. If you have the console output too many things (such as executing many cfg files, as one may have to do when playing team fortress on a handheld console,) it will crash the game. This isn't too big of a problem because you can just put the clear command in each of your configs so that it clears the console.
2. If you type a command that changes the map into the console, it will leave the keyboard in the corner and not let you use any controls, leaving you frozen there.
3. If you look out of bounds, the game will immediately crash.
4. If you attempt to start a new game while a game is already running, you will be locked in an infinite loop asking if you want to start a new game.
5. For some reason it doesn't seem to understand some console commands from the mod when loaded (doesn't understand temp1 from Team Fortress?)
6. Occasionally, without warning, it will crash when trying to do too many things at once. This can happen when trying to change settings while hosting a game but more often just happens for no discernible reason.

**Comment by qwerty0s** [comment] 2016-08-23 22:47
also hardware gpu rendering when

**Comment by megidont** [comment] 2016-08-23 22:47
I don't know how to use github I didn't mean to close it help me

**Comment by Rinnegatamante** [comment] 2016-08-24 07:54
A couple of these errors should be easily fixable but others will be a lot harder to find what causes the crash without proper coredumps (like the out of bounds crash).

**Comment by Ch0wW** [comment] 2016-08-24 10:01
1) it's a problem related to the console, or even the command buffer. I'll increase it to make some tests. At the same time, could you send us the configs you used to make some deeper tests?
2) Issue fixed.
3) It's related to the rendering... Best is not to look out of bounds at all :P 
4) We can't do anything much, since it waits for a keypress that cannot be requested, so I disabled that check.
5) Yep, it's a mistake I made. Usually, mods were never using that CVAR, except TF, so I put it into a debug CVAR. That was fixed already.
6) Weird case: I had fun trying every possible thing to intentionally crash the engine, especially while hosting, and nothing happened. Maybe you went back to livearea for a few seconds?

**Comment by megidont** [comment] 2016-08-25 06:02
-1 Files should be attached to this. (norm.cfg was executed instead of config.cfg to ensure that if configs got saved while any of the buttons were being held, I wouldn't have to connect it to my computer again to fix them.)
[autoexec.cfg.txt](https://github.com/Rinnegatamante/vitaQuake/files/436259/autoexec.cfg.txt)
[bs.cfg.txt](https://github.com/Rinnegatamante/vitaQuake/files/436260/bs.cfg.txt)
[config.cfg.txt](https://github.com/Rinnegatamante/vitaQuake/files/436261/config.cfg.txt)
[norm.cfg.txt](https://github.com/Rinnegatamante/vitaQuake/files/436262/norm.cfg.txt)
[num1.cfg.txt](https://github.com/Rinnegatamante/vitaQuake/files/436263/num1.cfg.txt)
[num2.cfg.txt](https://github.com/Rinnegatamante/vitaQuake/files/436264/num2.cfg.txt)
-3 shouldn't be too hard to avoid that
-6 Nope, it was while running Team Fortress, hosting a server, and at the same time trying to change things in menus. It happened again when trying to change settings to start a server when already connected to one.

**Comment by Ch0wW** [comment] 2016-08-25 22:54
1) Issue is now fixed. It was because of a very low (and unoptimized) memory management: it wasn't able to allocate 900bytes. The issue should be fixed now. **I attached you the latest "unofficial" build.** (replace the eboot.bin in _ux0://app/QUAK00001_)

3) Reproducing it is truly random... Entering out of bounds can lead to a crash, and watching some directions could also lead to a crash a few seconds after being outside a map...
**EDIT: Tried it in E1M3, in the first room. Watching the next room (with the GL+Zombies) crashes, while any other wall won't. May help finding a hint against it.** 

6) Again, I've tried any possible combination, and the recent builds didn't affect me at all, no single crash appear...

[eboot.zip](https://github.com/Rinnegatamante/vitaQuake/files/438203/eboot.zip)

**To Rinne** : my pull request may arrive soon. And it's really big!

**Comment by Zeroba** [comment] 2016-08-25 23:28
As far as sporadic crashes go, I've only noticed random crashes after playing the game after waking the vita from sleep

**Comment by megidont** [comment] 2016-08-26 01:33
-7 if you start a new server with a screen effect such as lava on, you will continue to see it.

**Comment by Ch0wW** [comment] 2016-08-26 09:45
**EDIT#1: About issue 3, Increasing the heapsize helps, but it crashes because of a too high number of vertices visible**

Issue 7 fixed. However, fixing the generated v_cshift, such as the QTF demo on startup is a bit risky yet, so I also added a hacky fix. Newest build (9c1125f) attached.
[eboot.zip](https://github.com/Rinnegatamante/vitaQuake/files/438971/eboot.zip)

@Zeroba : Apparently, I may have some hints about it. Here's what I'm usually looking at the log.txt whenever it happens:
`Mod_LoadBrushModel: progs/eyes.mdl has wrong version number (0 should be 29)
progs.dat has wrong version number (1179011410 should be 6)
Draw_TransPic: bad coordinates
progs.dat has wrong version number (0 should be 6)` 

Whenever it comes back from sleep, what about discharging and reloading everything in its memory?

**Comment by Ch0wW** [comment] 2016-08-28 01:21
This PSP2Dump should help with the noclip bug **(Error 3)**.
[psp2core-1472347030-0x00015b30b1-eboot.bin.psp2dmp.zip](https://github.com/Rinnegatamante/vitaQuake/files/440939/psp2core-1472347030-0x00015b30b1-eboot.bin.psp2dmp.zip)

**Comment by Rinnegatamante** [comment] 2016-08-28 18:29
All these bugs should be solved now.

@Zeroba sleep mode causes several issues with I/O Handles as said here: https://github.com/Rinnegatamante/vitaQuake/issues/6

It's definitely not related to this.

**Closed as completed** 2016-08-28 18:30 UTC
